// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCysawS-2AEYcKoITyCFI3AO1MWARU3Bx8',
    appId: '1:457224737198:web:ec697ae589050e74d6f83f',
    messagingSenderId: '457224737198',
    projectId: 'toureguideapp',
    authDomain: 'toureguideapp.firebaseapp.com',
    storageBucket: 'toureguideapp.firebasestorage.app',
    measurementId: 'G-4NRQB245YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlffGXAsy47KQODLGeCzZPqGvZ95xN2as',
    appId: '1:457224737198:android:73b4e18d82e7d15dd6f83f',
    messagingSenderId: '457224737198',
    projectId: 'toureguideapp',
    storageBucket: 'toureguideapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCrs_I_IEUzFlOxOgfcHZ8vk3jS6zZgSM',
    appId: '1:457224737198:ios:ac7fbddc4614deedd6f83f',
    messagingSenderId: '457224737198',
    projectId: 'toureguideapp',
    storageBucket: 'toureguideapp.firebasestorage.app',
    iosBundleId: 'com.example.tourguideapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCrs_I_IEUzFlOxOgfcHZ8vk3jS6zZgSM',
    appId: '1:457224737198:ios:ac7fbddc4614deedd6f83f',
    messagingSenderId: '457224737198',
    projectId: 'toureguideapp',
    storageBucket: 'toureguideapp.firebasestorage.app',
    iosBundleId: 'com.example.tourguideapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCysawS-2AEYcKoITyCFI3AO1MWARU3Bx8',
    appId: '1:457224737198:web:230525bff7d6bffbd6f83f',
    messagingSenderId: '457224737198',
    projectId: 'toureguideapp',
    authDomain: 'toureguideapp.firebaseapp.com',
    storageBucket: 'toureguideapp.firebasestorage.app',
    measurementId: 'G-QJJ5MPSMQH',
  );
}
